default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>